import type { Metadata } from "next";
import { Fira_Sans, Inter } from "next/font/google";
import "./global.css";
import { cn } from "@/lib/utils";

const fira = Fira_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("relative, h-full font-sans antialiased", fira.className)}
      >
        <main className="relative flex flex-col min-h-screen">
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
